### ISSUE TITLE
docker-compose.yaml that allows restore

### ISSUE THREAD

**Issue by jshank** [jaymoulin/docker-rpi-google-cloudprint#7]
I'm trying to daemonize this with docker-compose but have been unable to get it to restore and start properly. Do you have any recommendations on how to do this?

```yaml
version: "3" 
services:
   cloudprint:
     image: "jaymoulin/google-cloudprint"
     restart: always
     privileged: true
     volumes:
       - "./config:/root"
     ports:
        - "631:631"
     environment:
        TZ: America/Los_Angeles
        CUPS_USER_ADMIN: admin
        CUPS_USER_PASSWORD: supersecret
```

**Comment by jaymoulin** [comment]
You can `docker-compose exec cloudprint configure save` to copy your token + configuration to your `./config` folder and `docker-compose exec cloudprint configure load` to reload your configuration

**Comment by jshank** [comment]
That works as long as the initial container is running. After the first run, it appears to no longer have access to the configuration files since they are stored outside of the container. The container dies and exits before I can load the configuration

**Comment by jaymoulin** [comment]
What is your process and logs associated?

**Comment by jshank** [comment]
I've created the file above to run the container. On all subsequent runs, I receive the following:

```
Creating network "googlecloudprint_default" with the default driver
Creating googlecloudprint_cloudprint_1 ... done
Attaching to googlecloudprint_cloudprint_1
cloudprint_1  | Setting DEBUG-level logging
cloudprint_1  | No printers found
googlecloudprint_cloudprint_1 exited with code 0
```

**Comment by jshank** [comment]
I think I've created a workaround. I ran the image first time with an empty host folder mapped to the container /root folder and was able to successfully run `configure open`. I then used the cups web interface to configure the printer and then ran `configure close` to initiate the cloudprint linking workflow. I finally executed "configure save" per the README. I then modified the docker-compose.yaml file as below to map the backed-up `/root/cups` directory to `/etc/cups` inside the container. There is now no need to use `configure save` since the cups configuration directory is mapped to the host volume.

```
version: "3"
services:
  cloudprint:
    image: "jaymoulin/google-cloudprint"
    restart: always
    privileged: true
    volumes:
      - "./config:/root"
      - "./config/cups:/etc/cups"
    ports:
       - "631:631"
    environment:
       TZ: America/Los_Angeles
       CUPS_USER_ADMIN: admin
       CUPS_USER_PASSWORD: verysecure
```
