### ISSUE TITLE
avahi-daemon not running

### ISSUE THREAD

**Issue by dantebarba** [jaymoulin/docker-rpi-google-cloudprint#8]
I started the daemon with docker using the same command line from the readme.md. When I try to access any kind of option in the control panel I get 500 Server Error. I checked the logs and I saw this:

`Unable to communicate with avahi-daemon: Daemon not running
`

I'm using Debian (open media vault).

Docker version 18.09.4, build d14af54
Kernel: 4.19.0-0.bpo.2-amd64
Connected printer is a Samsung SCX-4200.

**Comment by jaymoulin** [comment]
> When I try to access any kind of option in the control panel I get 500 Server Error. 

How did you perform this?
Did you `docker exec cloudprint configure open` before trying to configure something?

**Comment by dantebarba** [comment]
Yes I did. Maybe it's because OMV is already running avahi on the host?.

PS: this image includes both CUPS and Google Cloud Print connector right?

**Comment by jaymoulin** [comment]
Docker purpose is to isolate so, no matter if avahi is running or not on the host.
This repository provides fully working docker images and you don't have to do anything else than what's described in the README file.

How are you trying to configure your container?

**Comment by dantebarba** [comment]
I first tried using a docker-compose configuration based on your docker run line:

`docker run -d --privileged --restart=always -v /dev/bus/usb:/dev/bus/usb -v "$HOME/.cloudprint/":/root --name cloudprint -e CUPS_USER_ADMIN=admin -e CUPS_USER_PASSWORD=password -p 631:631 jaymoulin/google-cloudprint`

```yaml
version: '2'

services:
  cloudprint:
    image: jaymoulin/google-cloudprint
    container_name: cloudprint
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ${CLOUDPRINT_CONFIG}/cups:/etc/cups
      - ${CLOUDPRINT_CONFIG}/credentials:/root
    environment:
      CUPS_USER_ADMIN: admin
      CUPS_USER_PASSWORD: ${CUPS_USER_PASSWORD}
    ports:
      - 631:631
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:printer.${DOMAIN_URL}"
      - "traefik.basic.port=631"
      - "traefik.basic.protocol=http"
    networks:
      - main

networks: 
  main:
    external: true
```

The container didn't start (it died exiting with code 0). So I removed the container and started using the readme line (docker run...). Container starts, control panel starts, but log shows avahi is not running.
